### ISSUE TITLE
Somethign is not working

### ISSUE THREAD

**Issue by Embiggenerd** [stephengardner/docker-node-typescript#3]
Runnign docker-compose up I get these errors:

error TS5033: Could not write file '/home/app/appDir/dist/index.js': EACCES: permission denied, open '/home/app/appDir/dist/index.js'.

error TS5033: Could not write file '/home/app/appDir/dist/index.js.map': EACCES: permission denied, open '/home/app/appDir/dist/index.js.map'.

To install @types I had to change owner on node_modules in local environment, weird

Recompilation in container does not happen as advertised, really nothing works as advertised.

**Comment by stephengardner** [comment]
Hey @Embiggenerd, this has been working for some time now without hiccup, so I'm wondering if you can provide reproduction steps to better diagnose the issue that you are having, since it seems to be unique to the setup that you are using.  Please provide version/environment information and reproduction steps (though I imagine you're just installing and running).

Thank you

**Comment by Embiggenerd** [comment]
I'm on linux mint 19

Docker version 18.09.1, build 4c52b90

docker-compose version 1.23.2, build 1110ad01

npm version 6.6.0

I'm literally just cloning, then cd, then docker-compose up. 

I tried npm install Node-Docker-Typescript. This literally only provides a nod_modules folder and a package-log.json

I'm a newbie to docker, so I know I am making some obvious mistake somewhere. 

Thanks for quick reply.

edit: node_modules permissions has to do with how npm works on my end.

**Comment by catman85** [comment]
I have the exact same problem. Any solution for this?
